server:
  port: "8080"
  mode: debug

database:
  driver: sqlite
  path: ./data/living-recorder.db

ffmpeg:
  path: ffmpeg

storage:
  default: local
  local:
    path: ./recordings
  s3:
    endpoint: ""
    access_key: ""
    secret_key: ""
    bucket: ""
    region: ""

mediamtx:
  url: "http://localhost:8889"
  rtmp_url: "rtmp://localhost:1935"
  preview_retry: 60

recorder:
  max_parallel: 10
  restart_on_failure: 3
  health_check_interval: 60
  health_check_timeout: 120
  default_video_codec: "copy"
  default_audio_codec: "copy"
  default_output_template: "{name}/{date}_{time}.mp4"
